% Input: sequence of actions and rewards
% Output:
%   - Value of BIC for each of the 5 models
%   - Identity of model with best BIC (1-5)
%   - Vector of length 5 with "1" for winning model and "0" for others

% SQ:Modify the function output to return model parameters
function [all_XFits, param, BIC, iBEST, BEST] = fit_all_v1_ZI(a, r)

% fit all 5 candidate models on the sequence of actions and rewards
% generated by either model.
% returns BIC for each model and store in "BIC".

% SQ:Modify the three lines below to return model parameters as well
[XFit_rand, ~, BIC(1)] = fit_M1random_v1(a, r);
[XFit_wsls, ~, BIC(2)] = fit_M2WSLS_v1(a, r);
[XFit_rw, ~, BIC(3)] = fit_M3RescorlaWagner_v1(a, r);

all_XFits = {XFit_rand, XFit_wsls, XFit_rw};

% find the identity of the model that has the best BIC.
% NB: As seen in Lecture, a lower BIC indicates a better fit.
[M, iBEST] = min(BIC);

BEST = BIC == M;

% returns identity of winning model as a vector.
BEST = BEST / sum(BEST);

param = all_XFits{iBEST};